{{- if not .Values.statefulset.disabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "orange.fullname" . }}
  labels:
    {{- include "orange.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orange.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orange.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: my-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: my-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
        storageClassName: {{ .Values.storage.storageClassName }}
{{- end }}
